{% set version = "1.7.5" %}

package:
  name: pytest-forked
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pytest-forked/pytest_forked-1.7.5.tar.gz
  sha256: 00f2bee51612f29b8e6b81eed2c3b2975e824c2693394f5bdaf7a1369078ba5f

build:
  skip: true  # [py<310]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - pytest >=3.1.0
    - setuptools_scm
    - setuptools >=41.4
    - setuptools-scm >=3.3
  run:
    - python
    - pytest >=7
    - py

test:
  imports:
    - pytest_forked
  files:
    - dummy_test.py
  commands:
    - pytest --forked dummy_test.py
    - pip check
    - pip check
    - pip check
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pytest-dev/pytest-forked
  license: MIT
  license_file: LICENSE
  summary: run tests in isolated forked subprocesses
  dev_url: https://github.com/pytest-dev/pytest-forked

extra:
  recipe-maintainers:
    - nicoddemus
