# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "VvL0gdPozl8wYi3fQVzZneG12QiSNeQJ0Qvf7lbBJvrHkGQ6BwL0UNcHsSz6mKVpquhbltPMraLnY1aOq7GkkY2ym7ChlwAe17WNQp4W2FUxwWRy3QwwNbzKJq9ugMFN5Z/IXK/IDCftp/4dRLARetFYHSWR1O5PkMxEljYyz1d7ROcQoEYz/PufvDfv9+IzrK0g4sbKP1aNIlaF0Rw8w6vucemxGcE5sTGkOhkClWDqwll9KfF5qQCa5LYxfgVlJdR3ngtQZRpxtLhxk4BvoMJIl4hrXGcDaYrXlBSAPV2EhhpnfXQXwv9+/6a506PUMMI1tZMcQhlsjMKc558WUnTS/7dWDVDWtuF9RRKFDxHybAcntAxp58BadNiAr45UtZ6PSXQfNlohPA6ZDMjpZQvO0XgY7AeiaWUT+3tpnzOwg0quLnaZ6jSOrA5eil05d3QL5SOHejpqHZU4K2BeHcJzQJdX8qNB2ATqphHEZF2EGepYF92pA8Bzs7QExuTlBndzJtKT8DK/q+56JBm47NZ1idsKtrrOLyACcYGbpd8GqwqnPV4euiXS/1uS7xVy9ZvrbU3VJ1T6hTB5tPYOm8mhegi/zDz6yHNns3GPOfDkdFylTRwVRLIeH8K4/5PJlCDSHgtZuKSun2/7WLTojUHlwqOdqVzvTS2Nbc5qb3s="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
