travis:
  secure:
    BINSTAR_TOKEN: AbK0nGxfHjvseEvi9q/uJGlWb8t7HSFscOh/qyrLEYnSpHDIZ0mtNE2sSXF8kF0L7tD1QLrwyYcaR83rYjNg7s+H4u9TnUaCxOVb/713N2Aakkujel99JHjg5bYQWi9XRrOsdoSt+njXhtRLCnLwZwv8wwQDByZyFM+rcg9YJ0b5REPTo4lNMBdu9Iy5ylfjJNgstKek/84gOmRIVSOBma+q4fyZBrgvrKSXXZEppkvEzufUhpmNHLrOWL6jYnggap0hX3h8zzJE7lNEn7yP0inikwRVX791qYy88LoZrdC+ViL3x9DK1wjPud/yfvPetbLoaMAOIPTgvJfinoigbdfVu2DZYnmqVlKEVA7DngDJR/f9L6S+QnqxoXi6jPL7g9xFmF8qihCf91oz9JV5GsCs88CJUzyw29cFlYWXdHEPhrLkR7RH4uyfRrfBk0RAZb6IrrsfuyHDLWooKc4n8WvHs643EC1V9j6Iu0k8NIM4M2gv4qLWdYwTOW2GPmCe9jsop0ALW3JJ8084PQSLmNu/jksVqlPa7fAXbSMUzuvoI9Hbsi4v/MKzBAR+L9DXWnmHDPDXu7pbca0Lw3cDJkviIDmBnI6RsHWJ4NYL0oe8WAEjDV9so+YPVaYGSijZbGlN5cCGhvviAhYFN4Dydf4VdSFdUYhpqVNbYfVA/Wo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
