travis:
  secure:
    BINSTAR_TOKEN: VvL0gdPozl8wYi3fQVzZneG12QiSNeQJ0Qvf7lbBJvrHkGQ6BwL0UNcHsSz6mKVpquhbltPMraLnY1aOq7GkkY2ym7ChlwAe17WNQp4W2FUxwWRy3QwwNbzKJq9ugMFN5Z/IXK/IDCftp/4dRLARetFYHSWR1O5PkMxEljYyz1d7ROcQoEYz/PufvDfv9+IzrK0g4sbKP1aNIlaF0Rw8w6vucemxGcE5sTGkOhkClWDqwll9KfF5qQCa5LYxfgVlJdR3ngtQZRpxtLhxk4BvoMJIl4hrXGcDaYrXlBSAPV2EhhpnfXQXwv9+/6a506PUMMI1tZMcQhlsjMKc558WUnTS/7dWDVDWtuF9RRKFDxHybAcntAxp58BadNiAr45UtZ6PSXQfNlohPA6ZDMjpZQvO0XgY7AeiaWUT+3tpnzOwg0quLnaZ6jSOrA5eil05d3QL5SOHejpqHZU4K2BeHcJzQJdX8qNB2ATqphHEZF2EGepYF92pA8Bzs7QExuTlBndzJtKT8DK/q+56JBm47NZ1idsKtrrOLyACcYGbpd8GqwqnPV4euiXS/1uS7xVy9ZvrbU3VJ1T6hTB5tPYOm8mhegi/zDz6yHNns3GPOfDkdFylTRwVRLIeH8K4/5PJlCDSHgtZuKSun2/7WLTojUHlwqOdqVzvTS2Nbc5qb3s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
